# -*- coding: utf-8 -*-
"""Visualizing Learner Handwriting with Dimensionality Reduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQJzuRmGV4Hstdko8yV9gmFdNV6GTwh5

#Project Title: Visualizing Learner Handwriting: Modeling Student Errors and AI Grading Bias with Dimensionality Reduction

##Context
In a simulated classroom setting, students submit their project via a online learning platform. An AI grading system evaluates these submissions automatically.

To ensure fairness and limit grading errors, we apply dimensionality reduction techniques—specifically PCA and t-SNE—to visualize how similar or ambiguous certain handwritten digits are. This helps us:

* Understand the AI grader's internal “perception” of student input,

* Diagnose potential misinterpretations,

* And improve grading accuracy so no student is penalized for legible but unconventional handwriting.

## Educational Purpose:

* Prevent misgrading due to handwriting variability.

* Promote transparency in AI grading systems.

* Help educators identify and address potential issues with automated grading tools.

## Project Scope

An AI system is responsible for evaluating students' handwritten digits (0–5). To simulate real-world classroom variability, we use the load_digits(n_class=6) dataset from sklearn as a proxy for diverse student handwriting.

We use dimensionality reduction to visually assess:

* Which digits are at risk of being misclassified,

* Whether grading clusters align well with actual digits,

* And how different techniques (PCA vs t-SNE) impact our understanding of grading behavior.
"""

#importing library
from time import time
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import offsetbox
from sklearn import manifold, datasets, decomposition

#loading the dataset
digits = datasets.load_digits(n_class=6)  # Digits 0 through 5 only
X = digits.data
y = digits.target
n_samples, n_features = X.shape
print(X.shape)  # (1083, 64)

"""####Interpretation:

Each image is 8×8 = 64 pixels, represented as 64-dimensional data. We simulate 1083 student submissions.

## Visualizing the data

Now, let's reduce the number of dimensions of the images, from 64 to 2, using PCA and t-SNE, to visualize the distribution of images in 2 dimensions.
"""

# t-sne embedding digits dataset
print ("computing t_SNE embedding")

t0 = time()
tsne = manifold.TSNE(n_components=2, init= 'pca', random_state = 0)
X_tsne = tsne.fit_transform(X)
t1= time ()
tsne_time = t1- t0
print ("t_SNE_embedding in time {}".format(tsne_time), '\n', X_tsne)
print("***************************")

#PCA Projection
print("PCA Projection")

t0 = time()
pca = decomposition.PCA(n_components=2)
X_pca = pca.fit_transform(X)

t1 = time()
pca_time = t1-t0
print("PCA projection in time {}".format(pca_time), '\n', X_pca)

"""#### Time Comparison:

t-SNE takes longer but gives clearer clusters.
"""

# Function to create scatter plot

def scatter(x, title = None) :
  x1 = []
  x2 = []

  plt.figure(figsize = (10,10))
  plt.title(title)
  for i in x :
    x1.append(i[0])
    x2.append(i[1])

  sns.scatterplot(x = x1, y = x2)
  plt.show()

scatter(X_tsne, "t_SNE embedding of the digits")
scatter(X_pca, "PCA Projection of digits")

"""## More Visualized Plot
We will use the plot_embedding function to get to a more advanced visualization. The clusters will still appear in the same way, but will be more informative with annotations.
"""

# Scale and visualize the embedding vectors
def plot_embedding(X, title=None):
    print(X)
    x_min, x_max = np.min(X, 0), np.max(X, 0)
    X = (X - x_min) / (x_max - x_min)

    plt.figure(figsize=(10,10))
    ax = plt.subplot(111)

    for i in range(X.shape[0]):
        plt.text(X[i, 0], X[i, 1], str(y[i]),
                 color=plt.cm.Set1(y[i] / 10.),
                 fontdict={'weight': 'bold', 'size': 9})
    if hasattr(offsetbox, "AnnotationBox"):

      shown_images = np.array([[1., 1.]])
      for i in range(X.shape[0]):
        dist = np.sum((X[i] - shown_images) ** 2, 1)
        if np.min(dist) < 4e-3:
            # don't show points that are too close
            continue
        show_images = np.r_[show_images, [X[i]]]
        imagebox = offsetbox.AnnotationBbox(offsetbox.OffsetImage(digits.images[i], cmap=plt.cm.gray_r), X[i])
        ax.add_artist(imagebox)

    plt.xticks([]), plt.yticks([])
    if title is not None:
        plt.title(title)

    plt.show()

plot_embedding(X_tsne, "t_SNE embedding of the digits (time %.2fs)" % (tsne_time))
plot_embedding(X_pca, "PCA Projection of digits (time %.2fs)" % (pca_time))

"""## Key Result
The t-SNE plot shows clear boundaries between digits. If certain digit clusters (e.g., 3 and 5) overlap in the 2D space, the AI grader might misinterpret a student's digit.

#Conclusion

This project demonstrates how dimensionality reduction techniques can:

* Increase fairness and transparency in AI-driven grading systems,

* Improve the fairness and transparency of AI-driven grading systems by visually highlighting areas prone to error.

By embedding student handwriting data into a 2D space, we can:

* Train AI models to better interpret ambiguous handwriting,

* Visualize overlapping clusters that could lead to grading errors,

* Visualize regions where handwriting may be misinterpreted.
"""